version: '3'
services:
  gateway:
    container_name: backend
    build:
      context: ../gateway
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "8080:8080"
    volumes:
      - "../gateway:/usr/src/app"
    depends_on:
      - mongodb
    logging: &logging
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "1"
    networks:
      - testApp
  frontend:
    container_name: frontend
    build:
      context: ../frontend
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
    volumes:
      - "../frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    logging:
      <<: *logging
    networks:
      - testApp
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27033:27017"
    volumes:
      - ../data/db:/data/db
      - ../data/seed:/data/seed
    restart: always
    logging:
      driver: none
    networks:
      - testApp

networks:
  testApp:
    driver: bridge
